version: "3"

services:
  server:
    build: ./
    container_name: yul-yort-server
    restart: always
    volumes:
      - ./src/:/app/src
    ports:
      - "9000:9000"
    depends_on:
      - mysql_db
    networks:
      - yul_yort
  mysql_db:
    container_name: mysql_db
    image: mysql:8
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - yul_yort
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yul-yort-test
    ports:
      - "3306:3306"
  phpMyAdmin:
    image: phpmyadmin
    restart: always
    networks:
      - yul_yort
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"

networks:
  yul_yort:
    driver: bridge

volumes:
  db: