version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./data-mongo:/data/db
  backend:
    build: .
    # image: top-api:latest
    container_name: top-api
    restart: always
    depends_on:
      - mongodb
    ports:
      - 9000:9000
    volumes:
      - ./src:/opt/app
      - ./.env:/opt/app/.env